<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['disk_usage_app_description'] = 'The Disk Usage Report app displays your system hard disk usage and provides a clickable drill down report.';
$lang['disk_usage_app_name'] = 'Disk Usage Report';
$lang['disk_usage_app_tooltip'] = 'Информация об использовании диска хранится в базе данных для быстрого поиска и обновляется каждые 24 часа. График, который Вы просматриваете, не выводит на экран информацию в реальном времени.  Щелкните по областям графика, чтобы перейти в папки и щелкнуть по \'cd.. \', чтобы возвратиться к предыдущей папке.';
$lang['disk_usage_coordinate_invalid'] = 'Координата недействительна.';
$lang['disk_usage_path_invalid'] = 'Путь является недопустимым.';
$lang['disk_usage_updating_disk_usage_information'] = 'Обновление информации об использовании диска. Это может занять несколько минут.';
