#!/bin/sh

TIMESTAMP=`date "+%b-%d-%Y-%T"`

# Set default configuration
#--------------------------

logger -p local6.notice -t installer "app-disk-usage-core - setting default configuration"

if [ -e /etc/ducrc ]; then
    cp /etc/ducrc /var/clearos/ducrc/backup/ducrc.$TIMESTAMP
fi

cp /usr/clearos/apps/disk_usage/deploy/ducrc /etc/ducrc
