<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['disk_usage_app_description'] = 'Diskanvändningsprogrammet visar användandet av ditt hårddisksutrymme och ger en klickbar rapport där du kan få en högre detaljeringsgrad.';
$lang['disk_usage_app_name'] = 'Diskanvändning';
$lang['disk_usage_app_tooltip'] = 'Diskanvändningsinformationen sparas i en databas för snabb upphämtning och uppdateras var 24 timme.   Grafen som du tittar på innehåller inte realtidsinformation.   Klicka på områden i grafen för att zooma in i mappar och klicka på \'cd..\' för att återgå till föregående mapp.';
$lang['disk_usage_coordinate_invalid'] = 'Samordningen är ogiltig.';
$lang['disk_usage_path_invalid'] = 'Sökvägen är ogiltig.';
$lang['disk_usage_updating_disk_usage_information'] = 'Uppdaterar diskanvändningsinformationen.   Detta kan ta flera minuter.';
