<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['disk_usage_app_description'] = 'The Disk Usage Report app displays your system hard disk usage and provides a clickable drill down report.';
$lang['disk_usage_app_name'] = 'Disk Usage Report';
$lang['disk_usage_app_tooltip'] = 'Diskanvändningsinformationen sparas i en databas för snabb upphämtning och uppdateras var 24 timme.   Grafen som du tittar på innehåller inte realtidsinformation.   Klicka på områden i grafen för att zooma in i mappar och klicka på \'cd..\' för att återgå till föregående mapp.';
$lang['disk_usage_coordinate_invalid'] = 'Samordningen är ogiltig.';
$lang['disk_usage_path_invalid'] = 'Sökvägen är ogiltig.';
$lang['disk_usage_updating_disk_usage_information'] = 'Uppdaterar diskanvändningsinformationen.   Detta kan ta flera minuter.';
