<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['disk_usage_app_description'] = 'Aplikacja użycia dysku wyświetla zajętość twardego dysku i oferuje interaktywny szczegółowy raport.';
$lang['disk_usage_app_name'] = 'Użycie dysku';
$lang['disk_usage_app_tooltip'] = 'Informacje o zajętości dysku twardego przechowywane są w bazie danych dla szybkiego dostępu do nich, uaktualniane są co 24 godziny.  Poniższy wykres nie przedstawia danych w czasie rzeczywistym.  Klikając w obszary wykresu można przechodzić do poszczególnych folderów, a klikając na \'cd..\' powracamy do folderu nadrzędnego.';
$lang['disk_usage_coordinate_invalid'] = 'Podana wartość jest nieprawidłowa.';
$lang['disk_usage_path_invalid'] = 'Ścieżka jest nieprawidłowa.';
$lang['disk_usage_updating_disk_usage_information'] = 'Aktualizuję informacje o zajętości dysku.  To może zająć trochę czasu.';
